version: "3"

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "4000:3000"
    restart: always

  mongodb:
    image: mongo
    container_name: todo-mongo
    ports:
      - "27017:27017"
